"""Loaders for the committed market-data snapshots.

The fixtures are real responses, stored gzipped: CBOE and OptionCharts
captured on 2026-08-11, and Nasdaq plus a matching OptionCharts fragment
captured on 2026-09-23 after the close -- the evening CBOE was found a full
session behind. They are never regenerated by the test suite --
their whole value is being a frozen, independently-sourced ground truth.
"""

from __future__ import annotations

import datetime as dt
import gzip
import json
from pathlib import Path

FIXTURE_DIR = Path(__file__).parent

# The session the snapshots were captured during. Tests pass this as "today"
# so expiry selection is deterministic forever, not dependent on the clock.
CAPTURE_DATE = dt.date(2026, 8, 11)

# Max pain values published by OptionCharts in the captured fragment, which
# our own computation must reproduce exactly.
OPTIONCHARTS_EXPECTED = {
    dt.date(2026, 8, 10): 215.0,
    dt.date(2026, 8, 12): 212.5,
    dt.date(2026, 8, 14): 210.0,
    dt.date(2026, 8, 17): 220.0,
}


def load_cboe_payload() -> dict:
    """The raw decoded NVDA chain snapshot."""
    with gzip.open(FIXTURE_DIR / "nvda_cboe.json.gz", "rt", encoding="utf-8") as handle:
        return json.load(handle)


def load_optioncharts_document() -> str:
    """The raw NVDA max-pain fragment."""
    with gzip.open(
        FIXTURE_DIR / "nvda_optioncharts.html.gz", "rt", encoding="utf-8", errors="replace"
    ) as handle:
        return handle.read()


# Nasdaq snapshot, 2026-09-23 after the close (expiries 2026-09-24 onward).
NASDAQ_RETRIEVED_AT = dt.datetime(2026, 9, 23, 23, 5)
NASDAQ_SESSION = dt.date(2026, 9, 23)


def load_nasdaq_payload() -> dict:
    """The raw decoded NVDA Nasdaq option-chain snapshot."""
    with gzip.open(FIXTURE_DIR / "nvda_nasdaq.json.gz", "rt", encoding="utf-8") as handle:
        return json.load(handle)


def load_optioncharts_document_20260923() -> str:
    """OptionCharts' NVDA max-pain fragment, captured alongside the Nasdaq snapshot."""
    with gzip.open(
        FIXTURE_DIR / "nvda_optioncharts_20260923.html.gz", "rt", encoding="utf-8",
        errors="replace",
    ) as handle:
        return handle.read()
