"""Loaders for the committed market-data snapshots.

The fixtures are real responses captured from CBOE and OptionCharts on
2026-08-11, stored gzipped. They are never regenerated by the test suite --
their whole value is being a frozen, independently-sourced ground truth.
"""

from __future__ import annotations

import datetime as dt
import gzip
import json
from pathlib import Path

FIXTURE_DIR = Path(__file__).parent

# The session the snapshots were captured during. Tests pass this as "today"
# so expiry selection is deterministic forever, not dependent on the clock.
CAPTURE_DATE = dt.date(2026, 8, 11)

# Max pain values published by OptionCharts in the captured fragment, which
# our own computation must reproduce exactly.
OPTIONCHARTS_EXPECTED = {
    dt.date(2026, 8, 10): 215.0,
    dt.date(2026, 8, 12): 212.5,
    dt.date(2026, 8, 14): 210.0,
    dt.date(2026, 8, 17): 220.0,
}


def load_cboe_payload() -> dict:
    """The raw decoded NVDA chain snapshot."""
    with gzip.open(FIXTURE_DIR / "nvda_cboe.json.gz", "rt", encoding="utf-8") as handle:
        return json.load(handle)


def load_optioncharts_document() -> str:
    """The raw NVDA max-pain fragment."""
    with gzip.open(
        FIXTURE_DIR / "nvda_optioncharts.html.gz", "rt", encoding="utf-8", errors="replace"
    ) as handle:
        return handle.read()
